oci8 debian

diff --git a/Dockerfile.debian.oci8.template b/Dockerfile.debian.oci8.template
--- a/Dockerfile.debian.oci8.template
+++ b/Dockerfile.debian.oci8.template
@@ -3,7 +3,34 @@ ARG UPSTREAM_VERSION
 FROM davyinsa/docker-nginx-php:${UPSTREAM_VERSION}
 
 
-# Copy from https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile and made some change to works with alpine.
+# always run apt update when start and after add new source list, then clean up at end.
+RUN set -xe; \
+    apt-get update -yqq && \
+    pecl channel-update pecl.php.net && \
+    apt-get install -yqq \
+      apt-utils \
+      gnupg2 \
+      #
+      #--------------------------------------------------------------------------
+      # Mandatory Software's Installation
+      #--------------------------------------------------------------------------
+      #
+      # Mandatory Software's such as ("mcrypt", "pdo_mysql", "libssl-dev", ....)
+      # are installed on the base image 'laradock/php-fpm' image. If you want
+      # to add more Software's or remove existing one, you need to edit the
+      # base image (https://github.com/Laradock/php-fpm).
+      #
+      # next lines are here becase there is no auto build on dockerhub see https://github.com/laradock/laradock/pull/1903#issuecomment-463142846
+      libzip-dev zip unzip && \
+      if [ ${LARADOCK_PHP_VERSION} = "7.3" ] || [ ${LARADOCK_PHP_VERSION} = "7.4" ] || [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then \
+        docker-php-ext-configure zip; \
+      else \
+        docker-php-ext-configure zip --with-libzip; \
+      fi && \
+      # Install the zip extension
+      docker-php-ext-install zip && \
+      php -m | grep -q 'zip'
+
 ###########################################################################
 # PHP OCI8:
 ###########################################################################
@@ -23,12 +50,7 @@ ENV OCI_VERSION=${ORACLE_INSTANT_CLIENT_MAJOR}
 
 RUN if [ ${INSTALL_OCI8} = true ]; then \
     # Install wget
-    apk add --no-cache wget \
-    linux-headers \
-    autoconf \
-    g++ \
-    make \
-    $PHPIZE_DEPS \
+    apt-get install --no-install-recommends -yqq wget \
     # Install Oracle Instantclient
     && mkdir /opt/oracle \
         && cd /opt/oracle \
@@ -41,7 +63,7 @@ RUN if [ ${INSTALL_OCI8} = true ]; then \
       && if [ ${OCI_VERSION} -lt 18 ] ; then ln -s /opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/libocci.so.${ORACLE_INSTANT_CLIENT_MAJOR}.${ORACLE_INSTANT_CLIENT_MINOR} /opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/libocci.so ; fi \
         && rm -rf /opt/oracle/*.zip \
     # Install PHP extensions deps
-    && apk add --no-cache --virtual .phpize-deps-configure $PHPIZE_DEPS \
+    && apt-get install --no-install-recommends -yqq \
       libaio-dev \
       freetds-dev && \
     # Install PHP extensions
