oci8 backup

diff --git a/Dockerfile.alpine.oci8.template b/Dockerfile.alpine.oci8.template
--- a/Dockerfile.alpine.oci8.template
+++ b/Dockerfile.alpine.oci8.template
@@ -1,36 +1,34 @@
-ARG UPSTREAM_VERSION
+ARG UPSTREAM_VERSION=8.3-alpine
 
 FROM davyinsa/docker-nginx-php:${UPSTREAM_VERSION}
 
-COPY docker-php-source /usr/local/bin/
-COPY docker-php-ext-* /usr/local/bin/
-# always run apt update when start and after add new source list, then clean up at end.
-RUN set -xe; \
-    apt-get update -yqq && \
-    pecl channel-update pecl.php.net && \
-    apt-get install -yqq \
-      apt-utils \
-      gnupg2 \
-      #
-      #--------------------------------------------------------------------------
-      # Mandatory Software's Installation
-      #--------------------------------------------------------------------------
-      #
-      # Mandatory Software's such as ("mcrypt", "pdo_mysql", "libssl-dev", ....)
-      # are installed on the base image 'laradock/php-fpm' image. If you want
-      # to add more Software's or remove existing one, you need to edit the
-      # base image (https://github.com/Laradock/php-fpm).
-      #
-      # next lines are here becase there is no auto build on dockerhub see https://github.com/laradock/laradock/pull/1903#issuecomment-463142846
-      libzip-dev zip unzip && \
-      if [ ${LARADOCK_PHP_VERSION} = "7.3" ] || [ ${LARADOCK_PHP_VERSION} = "7.4" ] || [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then \
-        docker-php-ext-configure zip; \
-      else \
-        docker-php-ext-configure zip --with-libzip; \
-      fi && \
-      # Install the zip extension
-      docker-php-ext-install zip && \
-      php -m | grep -q 'zip'
+# # always run apt update when start and after add new source list, then clean up at end.
+# RUN set -xe; \
+#     apt-get update -yqq && \
+#     pecl channel-update pecl.php.net && \
+#     apt-get install -yqq \
+#       apt-utils \
+#       gnupg2 \
+#       #
+#       #--------------------------------------------------------------------------
+#       # Mandatory Software's Installation
+#       #--------------------------------------------------------------------------
+#       #
+#       # Mandatory Software's such as ("mcrypt", "pdo_mysql", "libssl-dev", ....)
+#       # are installed on the base image 'laradock/php-fpm' image. If you want
+#       # to add more Software's or remove existing one, you need to edit the
+#       # base image (https://github.com/Laradock/php-fpm).
+#       #
+#       # next lines are here becase there is no auto build on dockerhub see https://github.com/laradock/laradock/pull/1903#issuecomment-463142846
+#       libzip-dev zip unzip && \
+#       if [ ${LARADOCK_PHP_VERSION} = "7.3" ] || [ ${LARADOCK_PHP_VERSION} = "7.4" ] || [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then \
+#         docker-php-ext-configure zip; \
+#       else \
+#         docker-php-ext-configure zip --with-libzip; \
+#       fi && \
+#       # Install the zip extension
+#       docker-php-ext-install zip && \
+#       php -m | grep -q 'zip'
 
 ###########################################################################
 # PHP OCI8:
@@ -48,25 +46,33 @@ ENV OCI_HOME="/opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}"
 ENV OCI_LIB_DIR="/opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}"
 ENV OCI_INCLUDE_DIR="/opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/sdk/include"
 ENV OCI_VERSION=${ORACLE_INSTANT_CLIENT_MAJOR}
+ENV PHP_URL="https://www.php.net/distributions/php-8.3.12.tar.xz"
 
-RUN if [ ${INSTALL_OCI8} = true ]; then \
-    # Install wget
-    apt-get install --no-install-recommends -yqq wget \
-    # Install Oracle Instantclient
-    && mkdir /opt/oracle \
+ADD https://raw.githubusercontent.com/docker-library/php/refs/heads/master/8.3/alpine3.20/fpm/docker-php-ext-configure /usr/local/bin/
+ADD https://raw.githubusercontent.com/docker-library/php/refs/heads/master/8.3/alpine3.20/fpm/docker-php-ext-enable /usr/local/bin/
+ADD https://raw.githubusercontent.com/docker-library/php/refs/heads/master/8.3/alpine3.20/fpm/docker-php-ext-install /usr/local/bin/
+ADD https://raw.githubusercontent.com/docker-library/php/refs/heads/master/8.3/alpine3.20/fpm/docker-php-source /usr/local/bin/
+
+
+RUN mkdir /opt/oracle \
         && cd /opt/oracle \
         && wget ${ORACLE_INSTANT_CLIENT_MIRROR}instantclient-basic-linux.${ORACLE_INSTANT_CLIENT_ARCH}-${ORACLE_INSTANT_CLIENT_VERSION}.zip \
       && wget ${ORACLE_INSTANT_CLIENT_MIRROR}instantclient-sdk-linux.${ORACLE_INSTANT_CLIENT_ARCH}-${ORACLE_INSTANT_CLIENT_VERSION}.zip \
       && unzip /opt/oracle/instantclient-basic-linux.${ORACLE_INSTANT_CLIENT_ARCH}-${ORACLE_INSTANT_CLIENT_VERSION}.zip -d /opt/oracle \
-      && unzip /opt/oracle/instantclient-sdk-linux.${ORACLE_INSTANT_CLIENT_ARCH}-${ORACLE_INSTANT_CLIENT_VERSION}.zip -d /opt/oracle \
-      && if [ ${OCI_VERSION} -lt 18 ] ; then ln -s /opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/libclntsh.so.${ORACLE_INSTANT_CLIENT_MAJOR}.${ORACLE_INSTANT_CLIENT_MINOR} /opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/libclntsh.so ; fi\
+      && unzip /opt/oracle/instantclient-sdk-linux.${ORACLE_INSTANT_CLIENT_ARCH}-${ORACLE_INSTANT_CLIENT_VERSION}.zip -d /opt/oracle
+
+RUN if [ ${OCI_VERSION} -lt 18 ] ; then ln -s /opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/libclntsh.so.${ORACLE_INSTANT_CLIENT_MAJOR}.${ORACLE_INSTANT_CLIENT_MINOR} /opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/libclntsh.so ; fi\
       && if [ ${OCI_VERSION} -lt 18 ] ; then ln -s /opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/libclntshcore.so.${ORACLE_INSTANT_CLIENT_MAJOR}.${ORACLE_INSTANT_CLIENT_MINOR} /opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/libclntshcore.so ; fi \
       && if [ ${OCI_VERSION} -lt 18 ] ; then ln -s /opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/libocci.so.${ORACLE_INSTANT_CLIENT_MAJOR}.${ORACLE_INSTANT_CLIENT_MINOR} /opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/libocci.so ; fi \
         && rm -rf /opt/oracle/*.zip \
     # Install PHP extensions deps
-    && apt-get install --no-install-recommends -yqq \
+    && apk add --no-cache php83-dev \
       libaio-dev \
-      freetds-dev && \
+      freetds-dev \
+      linux-headers \
+      autoconf \
+      g++ \
+      make && \
     # Install PHP extensions
     if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then \
       echo 'instantclient,/opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/' | pecl install oci8-2.0.12; \
@@ -78,11 +84,15 @@ RUN if [ ${INSTALL_OCI8} = true ]; then \
         echo "instantclient,/opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/" | pecl install oci8-3.2.1; \
     else \
       echo "instantclient,/opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION}/" | pecl install oci8; \
-    fi \
+    fi; \
+    mkdir -p /usr/src && \
+    cd /usr/src && \
+    curl -fsSL -o php.tar.xz "$PHP_URL" && \
+    chmod +x /usr/local/bin/docker-php* \
+    && apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS \
     && docker-php-ext-configure pdo_oci --with-pdo-oci=instantclient,/opt/oracle/instantclient_${ORACLE_INSTANT_CLIENT_VERSION},${ORACLE_INSTANT_CLIENT_MAJOR}.${ORACLE_INSTANT_CLIENT_MINOR} \
-        && docker-php-ext-configure pdo_dblib --with-libdir=/lib/x86_64-linux-gnu \
-        && docker-php-ext-install \
-                pdo_oci \
-        && docker-php-ext-enable \
-                oci8 \
-  ;fi
+    && docker-php-ext-configure pdo_dblib --with-libdir=/lib/x86_64-linux-gnu \
+    && docker-php-ext-install \
+            pdo_oci \
+    && docker-php-ext-enable \
+            oci8 \
